# Generated by Django 2.1.7 on 2019-02-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='idContent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
