# Generated by Django 2.1.7 on 2019-02-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_blog',
            name='tipeStatus',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
