# Generated by Django 2.1.7 on 2019-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190214_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_blog',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
    ]
